version: "2"

services:
  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/dumps:/dumps
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
  
  application:
    build:
      context: ./application
      args:
        UID: ${UID}
    image: application-image
    container_name: application
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      DEBUG: ${DEBUG}
    restart: always
    volumes:
      - ./docker/volumes/uploads:/var/www/html/wp-content/uploads
    ports:
      - "80:80"
